// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXRqsj0zwavJtRwzKHjxOMmxZKfhjfYec',
    appId: '1:133524587104:web:8e2c196d923128ad32b905',
    messagingSenderId: '133524587104',
    projectId: 'layanan-kependudukan',
    authDomain: 'layanan-kependudukan.firebaseapp.com',
    storageBucket: 'layanan-kependudukan.appspot.com',
    measurementId: 'G-0PWHKBP551',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDae6IKhGlLqliKjremKZCsy34b1UeSJrQ',
    appId: '1:133524587104:android:b7b1c28c8fb6fed132b905',
    messagingSenderId: '133524587104',
    projectId: 'layanan-kependudukan',
    storageBucket: 'layanan-kependudukan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB84YvvHpzry8Vt9SttaElZOIlZSLTLleg',
    appId: '1:133524587104:ios:a67f4be38782528b32b905',
    messagingSenderId: '133524587104',
    projectId: 'layanan-kependudukan',
    storageBucket: 'layanan-kependudukan.appspot.com',
    iosBundleId: 'com.example.layananKependudukan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB84YvvHpzry8Vt9SttaElZOIlZSLTLleg',
    appId: '1:133524587104:ios:f74eb8111250a67f32b905',
    messagingSenderId: '133524587104',
    projectId: 'layanan-kependudukan',
    storageBucket: 'layanan-kependudukan.appspot.com',
    iosBundleId: 'com.example.layananKependudukan.RunnerTests',
  );
}
